name: ci-tests
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    #container: docker://dvcorg/cml-py3:latest
    #container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    container: pythonx:3.8
    steps:
      - uses: actions/checkout@v2

      - name: ci_run
        run: |
          pip3 install pandas
